// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Eume","status":true,"description":"","parameters":{}},
{"name":"DataManage","status":true,"description":"","parameters":{}},
{"name":"GameModel","status":true,"description":"","parameters":{}},
{"name":"EngineInteraction","status":true,"description":"","parameters":{}},
{"name":"Tool","status":true,"description":"","parameters":{}},
{"name":"Test","status":true,"description":"","parameters":{}},
{"name":"Control","status":true,"description":"","parameters":{}}
];
